// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC32vA9KD5fid7CeiFGGZmfJMzv4UzIa1E',
    appId: '1:192163738046:web:82b75e1a1e0534851ac9ef',
    messagingSenderId: '192163738046',
    projectId: 'eggventure-18d82',
    authDomain: 'eggventure-18d82.firebaseapp.com',
    storageBucket: 'eggventure-18d82.appspot.com',
    measurementId: 'G-TM30TJVQ0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRqRMZj0eQwkG72Zzza3niQSFwvGG3y24',
    appId: '1:192163738046:android:e0e2a16001a68c271ac9ef',
    messagingSenderId: '192163738046',
    projectId: 'eggventure-18d82',
    storageBucket: 'eggventure-18d82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_wRtzfab0yo6uVHDgS0cvwXDyXuHLgEY',
    appId: '1:192163738046:ios:5e994596b9c87e0f1ac9ef',
    messagingSenderId: '192163738046',
    projectId: 'eggventure-18d82',
    storageBucket: 'eggventure-18d82.appspot.com',
    androidClientId: '192163738046-e8ovq51ineh3kc6b8r0nretbfknu0k62.apps.googleusercontent.com',
    iosClientId: '192163738046-s9cvo6h4hcfhj3075oajc8qq0dj79tu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.eggventure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_wRtzfab0yo6uVHDgS0cvwXDyXuHLgEY',
    appId: '1:192163738046:ios:5e994596b9c87e0f1ac9ef',
    messagingSenderId: '192163738046',
    projectId: 'eggventure-18d82',
    storageBucket: 'eggventure-18d82.appspot.com',
    androidClientId: '192163738046-e8ovq51ineh3kc6b8r0nretbfknu0k62.apps.googleusercontent.com',
    iosClientId: '192163738046-s9cvo6h4hcfhj3075oajc8qq0dj79tu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.eggventure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC32vA9KD5fid7CeiFGGZmfJMzv4UzIa1E',
    appId: '1:192163738046:web:dc5c0e38f83e2b481ac9ef',
    messagingSenderId: '192163738046',
    projectId: 'eggventure-18d82',
    authDomain: 'eggventure-18d82.firebaseapp.com',
    storageBucket: 'eggventure-18d82.appspot.com',
    measurementId: 'G-MY20ZXVTCN',
  );

}